INSERT INTO TB_TURMA (ID_TURMA, NOME) VALUES (TURMA_SEQ.NEXTVAL, '1SI');
INSERT INTO TB_TURMA (ID_TURMA, NOME) VALUES (TURMA_SEQ.NEXTVAL, '2SI');
INSERT INTO TB_TURMA (ID_TURMA, NOME) VALUES (TURMA_SEQ.NEXTVAL, '3SI');
INSERT INTO TB_TURMA (ID_TURMA, NOME) VALUES (TURMA_SEQ.NEXTVAL, '4SI');

INSERT INTO TB_GRUPO (ID_GRUPO, NOME) VALUES (GRUPO_SEQ.NEXTVAL, 'ARPA');
INSERT INTO TB_GRUPO (ID_GRUPO, NOME) VALUES (GRUPO_SEQ.NEXTVAL, 'SP COMPASS');
INSERT INTO TB_GRUPO (ID_GRUPO, NOME) VALUES (GRUPO_SEQ.NEXTVAL, 'INNTECH');
INSERT INTO TB_GRUPO (ID_GRUPO, NOME) VALUES (GRUPO_SEQ.NEXTVAL, 'KRAKEN');

INSERT INTO TB_ALUNO (ID_ALUNO, NOME, EMAIL, MENSALIDADE, ID_TURMA, ID_GRUPO) VALUES (ALUNO_SEQ.NEXTVAL, 'João Kleber', 'joaok@fiap.com.br', 1500.00, 1, 1);
INSERT INTO TB_ALUNO (ID_ALUNO, NOME, EMAIL, MENSALIDADE, ID_TURMA, ID_GRUPO) VALUES (ALUNO_SEQ.NEXTVAL, 'Claudio Silva', 'csilva@fiap.com.br', 1550.00, 2, 2);
INSERT INTO TB_ALUNO (ID_ALUNO, NOME, EMAIL, MENSALIDADE, ID_TURMA, ID_GRUPO) VALUES (ALUNO_SEQ.NEXTVAL, 'Alessandra Amaral', 'ale@fiap.com.br', 1400.00, 3, 3);
INSERT INTO TB_ALUNO (ID_ALUNO, NOME, EMAIL, MENSALIDADE, ID_TURMA, ID_GRUPO) VALUES (ALUNO_SEQ.NEXTVAL, 'Fernando Rodrigues', 'frodrigues@fiap.com.br', 1500.00, 4, 4);